// <autogenerated />
using MDD4All.EAFacade.ModelTree.ViewModels;
using MDD4All.UI.DataModels.Tree;
using Microsoft.AspNetCore.Components;

namespace MDD4All.UI.BlazorComponents.EnterpriseArchitect.ModelTree
{
    public partial class EaModelTreeView
    {
        [Parameter]
        public RepositoryTreeViewModel DataContext { get; set; }

        void OnSelectionChanged(ITreeNode node)
        {
            DataContext.SelectedNode = node;
        }
    }
}