// <autogenerated />
using Microsoft.AspNetCore.Components;

namespace MDD4All.UI.BlazorComponents.EnterpriseArchitect.ModelTree
{
    public partial class ModelTreeIcon
    {
        [Parameter]
        public string Icon { get; set; }
    }
}